### ISSUE TITLE
1.0.0 broke time travelling and hot reloading

### ISSUE THREAD

**Issue by minedeljkovic** [salsita/redux-side-effects#14]
In version 1.0.0 effects are deferred from enhanced reducers even on dispatch initiated by redux dev tools, during time travelling or reducer hot reloading.
If I remember well, one of main goals of redux-side-effects was not to brake any of dev tools functionality.
Is there a workaround for this, or am I missing something about new implementation?

**Comment by tomkis** [comment]
This indeed must a bug. Let me investigate and get back to you. I didn't realize that this breaking change could potentially break devtools. Definitely top priority now.

**Comment by tomkis** [comment]
Fixed in 1.0.1

**Comment by minedeljkovic** [comment]
This fixed half of the problem - hot reloading. Time traveling still executes effects.

Problem is that devtools liftedStore, during time travelling, dispatches to same enhanced reducer, which then deffer effects to side effects enhanced store (one created by createEffectCapableStore).

I think side effects enhanced store should ignore effects while not dispatching (i.e. while some other store like liftedStore dispatches). 
Problem is it is not so easy to check who is dispatching. 
Wrapping dispatch is not 100% accurate since original store dispatches once before returning dispatch to be wrapped ([https://github.com/reactjs/redux/blob/master/src/createStore.js#L204](https://github.com/reactjs/redux/blob/master/src/createStore.js#L204)). I wonder if this was a bug in previous version of redux-side-effects :)

I will try to look more into this. @tomkis1 Do you have any idea, how this could be solved?

**Comment by tomkis** [comment]
Oh sorry, didn't realize that you mean time travelling too I checked only the "devtools" part.

>  I wonder if this was a bug in previous version of redux-side-effects :)

Absolutely! This is the main reason why I made the decision to rewrite it, there was no other option to work it around. I wanted to keep the behaviour consistent but now it's obvious we'll have pretty hard times figuring out how to make time travel working.

**Comment by tomkis** [comment]
@minedeljkovic after @gaearon decided to close the PR (and his decision was right) and me [realizing](https://github.com/reactjs/redux/issues/465#issuecomment-205047706) that it does make sense to provide custom initialize function i've decided to go back with wrapped `dispatch`.

I'll fix this issue by using wrapped version of `dispatch` instead of executing side effects in every reducer call.
