### ISSUE TITLE
Get this in Redux docs

### ISSUE THREAD

**Issue by calebmer** [salsita/redux-side-effects#6]
This is a really cool package, can we possibly get it in the [redux Ecosystem](http://redux.js.org/docs/introduction/Ecosystem.html) docs?

**Comment by tomkis** [comment]
Thank you! That's a great idea. We could possible send a PR but I would like to provide the real world example first. This package also needs a bit more documentation and explanation, there is also a blog post coming along and the first part of it has been already released http://blog.javascripting.com/2015/12/08/the-human-brain-is-a-vital-front-end-component/ the second part though will be much more important.

**Comment by tomkis** [comment]
Closing, http://redux.js.org/docs/introduction/Ecosystem.html#enhancers
